name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  REGION: ${{ secrets.AWS_REGION }}
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set region $AWS_REGION

    - name: Login to Amazon ECR
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY
    
    - name: Build Docker image
      run: |
        docker buildx build --platform linux/arm64 -t my-lambda-function .

    - name: Tag Docker image
      run: |
        docker tag my-lambda-function:latest ${{ secrets.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

    - name: Update Lambda function
      run: |
        aws lambda update-function-code --function-name mylambdastack-LambdaFunction-V79cQI3FIzzY --image-uri ${{ secrets.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} --region ${{ secrets.AWS_REGION }}

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest
